
mqtt:
  host: ${HA_MQTT_HOST}
  port: ${HA_MQTT_PORT}
  username: ${HA_MQTT_USERNAME}
  password: ${HA_MQTT_PASSWORD}
hass:
  device_name: Hass Linux Companion Tests
  device_id: hass_linux_companion_tests

devices:
  naga_epic_chroma:
    name: Naga Epic Chroma


entities:
  switches:
    - name: Echo_boolean
      id: echo_boolean
      command_on: "echo True > /tmp/ha_companion"
      command_off: "echo False > /tmp/ha_companion"
      binary_sensor:
        type: command
        command: "cat /tmp/ha_companion"
        polling_rate: 1
        parse:
          - type: bool

  buttons:
    - name: Echo_True
      id: echo_true
      command: "echo True > /tmp/ha_companion"    
  binary_sensors:
    - name: Echo boolean sensor
      id: echo_boolean_sensor
      type: command
      command: "cat /tmp/ha_companion"
      polling_rate: 1
      parse:
        - type: bool
  selects:
    - name: Select
      id: select
      type: command
      command_template: "echo {} > /tmp/ha_companion_select"
      state_map:
        # Value to be displayed in Home Assistant: Value to be passed to command
        On: "True"
        Off: "False"
        Offn: Somewhere_in_the_middle
      sensor:
        type: command
        command: "cat /tmp/ha_companion_select"
        polling_rate: 1
        parse:
         - type: bool
          
